---
- hosts: all
  become: yes
  gather_facts: false
  ignore_errors: true
  vars:
    user_name: serge2027
    collor: red

  tasks:
    #  - name: install softwares
    #    package:
    #     state: present
    #     name: 
    #       - wget
    #       - ntp
    #       - finger
    #       - curl
    #  - name: Install softwares
    #    package:
    #     state: present 
    #     name: "{{ item }}"
    #    with_items:
    #        - wget
    #        - ntp
    #        - finger
    #        - curl
     - name: Check uptime
       command: uptime
       tags:
         - cm
     - name: Install softwares
       package:
        state: present
        name: "{{ item }}"
       loop:
         - wget
         - finger
         - curl
         - ntp

     - name: Install passwd package
       apt:
          name: passwd
          state: present
       when:  ansible_distribution not in "Debian, Ubuntu"
       tags:
         - app1
     - name: create group
       group:
          name: cloudteam
          state: present
#       when: ansible_distribution_major_version < 9
     - name: Create user
       user:
          name: "{{user_name}}"
          comment: Serge Admin
          group: cloudteam

- hosts: db
  become: yes
  gather_facts: no
  tasks:
     - name: install apache
       apt: 
         name: apache2
         state: present
     - name: Start apache service
       service: name=apache2 state=started enabled=yes
       tags:
         - service
     - name: Copy index file 
       copy:
         src: index.html
         dest: /var/www/html/index.html 
         mode: '0644'  
     